steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-app:$SHORT_SHA', '.']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/my-app:$SHORT_SHA']

  - name: 'gcr.io/cloud-builders/kubectl'
    args: [
      'set', 'image', 'deployment/telegram', 
      'my-app-sha256-1=gcr.io/$PROJECT_ID/my-app:$SHORT_SHA', 
      '--namespace', 'default'
    ]
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=telegram-cluster'
    
timeout: '1200s'

options:
  logging: CLOUD_LOGGING_ONLY
